name: Hello World

on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - name: Post text to a Slack channel
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ secrets.SLACK_BOT_TOKEN }}
        payload: |
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: "hey <@channel>!"
